theme: jekyll-theme-merlot

title: 'Yiyong(Rambo) Zhao: Curriculum Vitae 赵义勇: 个人主页'

description: 'Yiyong(Rambo) Zhao (赵义勇), Postdoctoral Research Fellow in Bioinformatics at Harvard University. Specialized in Genomcis and Bioinfromatics Research'
