theme: jekyll-theme-merlot

title: 'Yiyong Zhao: Curriculum Vitae 赵义勇: 个人简历'

description: 'Postdoctoral Research Fellow in Bioinformatics at Harvard University. Specialized in Genomcis and Bioinfromatics Research'
